name: CICD Notification to Telegram

on: [push, issues, create, pull_request]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
    - name: Notify on Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: There is a new ${{ github.event_name }} event to ${{ github.repository }}.

    
  
