name: Release

on:
  create:
    tags: 
      - v* # as long as a tag starts with v, this yml will be triggered

jobs:
  release:
    name: Release on Github
    runs-on: ubuntu-latest
    steps:
      - name: Check out codes
        uses: actions/checkout@v2
        
      - name: Validate Go releaser configuration
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: check
          
      - name: Release on Github
        uses: docker://goreleaser/goreleaser:latest
        with:
          arg: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Notify on Telegram
        # You may pin to the exact commit or the version.
        # uses: appleboy/telegram-action@ae54341a85fdcf97cbea354678d7b8c062286c15
        uses: appleboy/telegram-action@0.0.3
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Your ${{ github.event_name }} is released on your Github.
    
  
  
