name: CICD Notification to Telegram

on: [issues]
    
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@master
    - name: Notify on Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Issue ${{ github.event.issue }} at ${{ github.repository }}.

    
  
